language: rust
rust:
  - stable
cache: cargo
scripts:
  - cargo build --verbose --all
  - cargo run --bin emit-skk-dictionary -- ./dist/SKK-JISYO.ongeki.utf8

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - ./dist/SKK-JISYO.ongeki.utf8
  skip_cleanup: true
  on:
    tags: true
