language: rust
rust:
  - stable
cache: cargo
script:
  - cargo build --verbose --all
  - cargo run -- -t skk ./dist/SKK-JISYO.ongeki.utf8
  - cargo run -- -t atok ./dist/ongeki-atok.txt
  - cargo run -- -t msime ./dist/ongeki-msime.txt

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - ./dist/SKK-JISYO.ongeki.utf8
    - ./dist/ongeki-atok.txt
    - ./dist/ongeki-msime.txt
  skip_cleanup: true
  on:
    tags: true
